# Specify defaults for testing
PREFIX = /dls_sw/prod/tools/RHEL5
PYTHON = $(PREFIX)/bin/python2.6
PYTHON_CONFIG = $(PYTHON)-config
INSTALL_DIR = $(PREFIX)/lib/python2.6/site-packages
SCRIPT_DIR = $(PREFIX)/bin
MODULEVER = 0.0

# Override with any release info
-include $(TOP)/Makefile.private
