# Specify defaults for testing
PVER = 2.6
PREFIX = /dls_sw/prod/tools/RHEL5
PYTHON = $(PREFIX)/bin/python$(PVER)
PYTHON_CONFIG = $(PYTHON)-config
INSTALL_DIR = $(PREFIX)/lib/python$(PVER)/site-packages
SCRIPT_DIR = $(PREFIX)/bin
MODULEVER = 0.0

# Override with any release info
-include $(TOP)/Makefile.private
