# Specify defaults for testing
PREFIX := $(shell pwd)/prefix
PYTHON = $(shell readlink -f $$(which dls-python))
SCRIPT_DIR = $(PREFIX)/bin
PVER = $(shell $(PYTHON) -c 'import sys; print "%d.%d" % sys.version_info[0:2]')
INSTALL_DIR = $(PREFIX)/lib/python$(PVER)/site-packages
MODULEVER = 0.0

# Override with any release info
-include $(TOP)/Makefile.private
